name: Build and deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 3 * * *' # 3:30 AM UTC (SBOMs regenerate at 2:30 AM UTC)

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-static:
    environment:
      name: github-pages
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Fix permissions
        run: |
          chmod -c -R +rX "dist/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist/

  deploy:
    needs: build-static
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: [self-hosted, Linux]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v4
